apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: harbor.example.com/my-project/database:1.0.0
        ports:
        - containerPort: 5432