name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
           registry: demo.goharbor.io
           username: ${{ secrets.HARBOR_USERNAME }}
           password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t demo.goharbor.io/myfirstapp/backend:$GITHUB_SHA -f backend/Dockerfile .

      - name: Push Docker image
        run: |
          docker push demo.goharbor.io/myfirstapp/hello-world:$GITHUB_SHA