name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd frontend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

            - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
           registry: demo.goharbor.io
           username: ${{ secrets.HARBOR_USERNAME }}
           password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t demo.goharbor.io/myfirstapp/frontend:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push demo.goharbor.io/myhwapp/frontend:$GITHUB_SHA