name: Test Harbor Login

on:
  # Manual trigger option
  workflow_dispatch:

jobs:
  test-harbor-login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: demo.goharbor.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        
    - name: Verify Login
      run: |
        echo "Harbor login successful!"
        docker info
